# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-02 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleToTag',
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='article',
            name='describe',
            field=models.TextField(max_length=500, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='article',
            name='istop',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
        migrations.AlterField(
            model_name='category',
            name='rank',
            field=models.IntegerField(unique=True, verbose_name='序号'),
        ),
    ]
