# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_reply_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='邮箱地址'),
        ),
    ]
